FROM python:3.8.12

WORKDIR /opt/app

RUN apt-get update && \
    apt-get -y upgrade && \
    apt-get install -yq --no-install-recommends build-essential gcc chrpath clang patchelf python3-dev && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN pip install pipenv

COPY Pipfile /opt/app
COPY Pipfile.lock /opt/app

RUN pipenv sync

COPY . /opt/app

RUN pipenv run nuitka3 main.py --follow-imports --standalone --remove-output --clang

ENTRYPOINT ./entrypoint-nuitka.sh
