FROM balenalib/raspberrypi3-python:3.8.3-stretch-build

RUN [ "cross-build-start" ]

WORKDIR /opt/app

RUN apt-get update && \
    apt-get -y upgrade && \
    apt-get install -yq --no-install-recommends build-essential gcc chrpath clang patchelf && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN pip install pipenv

COPY Pipfile /opt/app
COPY Pipfile.lock /opt/app

RUN pipenv sync

COPY . /opt/app

RUN pipenv run nuitka3 main.py --follow-imports --standalone --remove-output --clang

RUN [ "cross-build-end" ]

ENTRYPOINT ./entrypoint-nuitka-armv7l.sh
